### ISSUE TITLE
Update branding

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/fair-data-repository#20]
Whilst some brand customisations have been implemented already Imperial has since updated its branding materials so this needs to be revised.

**Comment by npapantonis** [comment]
Attaching some of the new branding logos (Blue, Black, and White versions) as they may be in accessible from the Imperial website
![Image](https://github.com/user-attachments/assets/3208a743-d74a-4f62-8a7a-bff5d37e3ee5)
![Image](https://github.com/user-attachments/assets/7e928925-f839-48c1-af08-596d5f747cdb)

**Comment by npapantonis** [comment]
See the following item for Imperial new logos:
https://github.com/ImperialCollegeLondon/fair-data-repository/issues/49

**Comment by Steven-Eardley** [comment]
Closing this; superseded by #49
