### ISSUE TITLE
Review Invenio Helm Charts

### ISSUE THREAD

**Issue by richard-jones** [ImperialCollegeLondon/fair-data-repository#35]
* PR: [when the PR is created, put a link to it here.  DO NOT use the "linked PR" feature]
* User Test Scripts: [when there are user test scripts available link them here]

---

Review the Helm charts for Invenio v12, and determine their current suitability for Imperial deployment, and identify any work required to bring them up to standard

# Acceptance Criteria

*List the criteria which must be met for the issue to be considered complete*

* A set of subsequent issues created which identify specific work to be done

**Comment by Steven-Eardley** [comment]
We've successfully installed both the vanilla demo site and branded dev instance of the Imperial repo on a cluster (on DigitalOcean) so we've navigated through the community helm charts and their limitations. Documentation will feed into our dev guide for Imperial. Closing.
