### ISSUE TITLE
Produce technical documentation on Data Models

### ISSUE THREAD

**Issue by richard-jones** [ImperialCollegeLondon/fair-data-repository#42]
* PR: [when the PR is created, put a link to it here.  DO NOT use the "linked PR" feature]
* User Test Scripts: [when there are user test scripts available link them here]

---

Produce documentation showing the data models required, may be derived from the Data Modelling breakout sessions.

# Acceptance Criteria

*List the criteria which must be met for the issue to be considered complete*

* A technical mapping description of the data models required in Invenio

**Comment by richard-jones** [comment]
@npapantonis @LalithaKambhammettu to note from today that this will feed into work possibly for the Library in providing an Admin Guide for the form

**Comment by richard-jones** [comment]
Data model docs here https://docs.google.com/spreadsheets/d/106fzB6EiVJmnd3kRmTc1HEkx2h8zTR2S8PFlr-_qMHY/edit

**Comment by npapantonis** [comment]
HI @Peters, ***@***.***>,

This is an GitHub Board item re “Produce technical documentation on Data Models” with the acceptance criteria of “A technical mapping description of the data models required in Invenio”.  It was noted by CL that this will feed into work possibly for the Library in providing an Admin Guide for the form; and Cottage Labs have appended the following (also attached) for you to review, accept, or update with any feedback

Data model docs here https://docs.google.com/spreadsheets/d/106fzB6EiVJmnd3kRmTc1HEkx2h8zTR2S8PFlr-_qMHY/edit

Please can you review this and let us know if you have any comments or if this ticket can be closed off?

Kind Regards,

Noel

**Comment by npapantonis** [comment]
@richard-jones @J4bbi @Steven-Eardley @cc-a FYI 

Wayne has agreed to keep "Subject/keywords" active as per our suggestion and given it had not been greyed out. "Rights" for the MVP, choice of CC0 and CC-BY is fine. Wayne may have misinterpreted the ‘only one license allowed’ comment and realised it refers to repeatability so makes absolute sense (and was probably added by Wayne originally). If there is a possibility/need for adding more licenses based on demand, we can look at this internally.
