### ISSUE TITLE
Azure Container registry

### ISSUE THREAD

**Issue by J4bbi** [ImperialCollegeLondon/fair-data-repository#61]
We will need a container registry to pull images of the instance from.

It is possible to create a new container registry through the dashboard and attach it to the InvenioRDM-Dev service by selecting Attach registry => Create new. 

Are we okay to do so @cc-a ?

Can I also confirm that the domain we will deploy to is http://invenio.rcs.ic.ac.uk/ ?

**Comment by cc-a** [comment]
The current workflow publishes the docker image to the github container registry - https://github.com/ImperialCollegeLondon/fair-data-repository/pkgs/container/fair-data-repository. I've now made the repository and the image publicly available so I believe it is suitable for use.

Not totally sure about the domain... In the short term I assume we can deploy to a *.azure.com subdomain.

**Comment by J4bbi** [comment]
Okay, that's grand @cc-a 

It's not clear to me however how to procure a *.azure.com domain. I've done some searching on their documentation but not yet found that. Do you know?

It seems to me that we need that for the ingress controller to work.

**Comment by cc-a** [comment]
This guide seems to cover things - https://learn.microsoft.com/en-us/azure/aks/ingress-tls?tabs=azure-cli. I've created a public IP in the resource group that you can use - https://portal.azure.com/#@ImperialLondon.onmicrosoft.com/resource/subscriptions/69bd6a7a-45bb-4e2e-bf55-1c7882b136a0/resourceGroups/invenio-dev/providers/Microsoft.Network/publicIPAddresses/invenio-dev/overview
