### ISSUE TITLE
[Theming] - Searched text font color is white and difficult to read

### ISSUE THREAD

**Issue by J4bbi** [ImperialCollegeLondon/fair-data-repository#68]
Having searched for "something" this is how it looks. With blue underline it seems.

![image](https://github.com/user-attachments/assets/dc143a40-6c37-4c68-92d3-3680c58130f8)

**Comment by amdomanska** [comment]
This issue has been moved to: https://github.com/ImperialCollegeLondon/fair-data-repository/issues/93
