### ISSUE TITLE
[Theming] Button color for edit is yellow

### ISSUE THREAD

**Issue by J4bbi** [ImperialCollegeLondon/fair-data-repository#69]
Very high contrast.

![image](https://github.com/user-attachments/assets/7a823c21-e0af-45a4-95f2-6d36e56469a9)

![image](https://github.com/user-attachments/assets/c79f5e86-2777-46bb-8e58-8a498b36356a)

**Comment by amdomanska** [comment]
This issue has been moved to: https://github.com/ImperialCollegeLondon/fair-data-repository/issues/93
