### ISSUE TITLE
Scope Phase 2

### ISSUE THREAD

**Issue by richard-jones** [ImperialCollegeLondon/fair-data-repository#84]

**Comment by npapantonis** [comment]
@richard-jones I have attached the listing as per our discussion.  The phases are now appended to the original requirements listing (with your comments) as additional tabs, covering Phase 1, 2, 3 etc. items.  If you can take a look at this and:

- populate the "Phase 1" tab with what you have/will deliver in this current SoW
- refine the "Phase 2" tab as per our discussion i.e. what can be delivered for an operational production service (live by Easter 2025)
- refine the "Phase 3" tab with any outstanding items not addressed in Phase 2

We can then discuss with the WG on Monday to inform them of what Phase 2 will potentially deliver for a baseline service and confirm back with you to progress an SoW.

[CottageLabs_Invenio_Imperial_FAIRDataRepositoryRequirementsCatalogue121124.xlsx](https://github.com/user-attachments/files/17718147/CottageLabs_Invenio_Imperial_FAIRDataRepositoryRequirementsCatalogue121124.xlsx)
