### ISSUE TITLE
Investigate backport of v13 community workflow feature

### ISSUE THREAD

**Issue by richard-jones** [ImperialCollegeLondon/fair-data-repository#95]
* PR: [when the PR is created, put a link to it here.  DO NOT use the "linked PR" feature]
* User Test Scripts: [when there are user test scripts available link them here]

---

Investigate what's involved in backporting the community workflow feature back from v13 to v12

# Acceptance Criteria

*List the criteria which must be met for the issue to be considered complete*

* We have an idea what work is involved and how long it might take
* We have community buy-in for us to carry out the work

**Comment by Steven-Eardley** [comment]
Complete
